#!/bin/bash

set -e

# Validate that right number of resources was created
cd /root/setup/terraform/tfc-registry
terraform_state=$(terraform state list | wc -l)
if [ $terraform_state -ne 8 ]; then
  fail-message "The terraform apply in /root/setup/terraform/tfc-registry did not create all 8 resources based on the terraform.tfstate file."
fi

exit 0
