#!/bin/bash

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

# CD to /root/gitclones/hashicups-application
cd /root/gitclones/hashicups-application

# Run terraform init to copy state to TFC
terraform init -force-copy

exit 0
