version: "3"
virtualmachines:
- name: terraform
  image: instruqt-hashicorp/terraform-workstation-0-14-9
  shell: /bin/bash
  machine_type: n1-standard-1
aws_accounts:
- name: terraform
  managed_policies:
  - arn:aws:iam::aws:policy/IAMFullAccess
  - arn:aws:iam::aws:policy/AmazonEC2FullAccess
  - arn:aws:iam::aws:policy/AmazonVPCFullAccess
