#!/bin/bash
#
# This script runs when the platform solve the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#
set -euxo pipefail

HISTFILE=/root/.bash_history
set -o history

declare -a challenge_commands=("vault status" "vault token lookup" "vault secrets list")

for cmd in "${challenge_commands[@]}";
do
  $cmd
done

exit 0
